### ISSUE TITLE
Add CI workflows to enhance the dev experience

### ISSUE THREAD

**Issue by umbynos** [arduino/setup-protoc#34]
### Describe the request

Add some checks workflows to this repo to enhance the developer experience and to catch common problems:
- https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/sync-labels.md
- https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-license.md
- https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-markdown-task.md
- https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-taskfiles.md

### Describe the current behavior

the CI status is not on pair with the team tooling standard

### 'arduino/setup-protoc' version

N/A

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/setup-protoc/issues?q=)
- [X] I verified the feature was still missing when using the latest version
- [X] My request contains all necessary details

**Comment by MatteoPologruto** [comment]
Check workflows added here:
- #37 
- #39 
- #40 
- #42
