### ISSUE TITLE
Node v12 is deprecated

### ISSUE THREAD

**Issue by hankolsen** [arduino/setup-protoc#45]
### Describe the request

Github Actions are deprecating workflows that are running on Node v12: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Please update the Node version used by setup-protoc to v16

### Describe the current behavior

Actions run in Github Actions will output warnings under the Annotations section.

### 'arduino/setup-protoc' version

arduino/setup-protoc@v1

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/setup-protoc/issues?q=)
- [X] I verified the feature was still missing when using the latest version
- [X] My request contains all necessary details

**Comment by umbynos** [comment]
Fixed in #48
