### ISSUE TITLE
API rate limit exceeded

### ISSUE THREAD

**Issue by ahrtr** [arduino/setup-protoc#63]
### Describe the problem

We are constantly getting this error recently,

```
Run arduino/setup-protoc@64c0c85d18e984422218383b81c52f8b077404d3
  with:
    version: 3.14.0
    include-pre-releases: false
Error: API rate limit exceeded for 40.84.170.113. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

I see a similar issue https://github.com/actions/setup-go/issues/16 , which I think you may refer to.

### To reproduce

We see this error each time when we merge a PR, 
https://github.com/etcd-io/etcd/blob/main/.github/workflows/static-analysis.yaml

### Expected behavior

Successful

### 'arduino/setup-protoc' version

v1.1.2

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/setup-protoc/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @ahrtr. You must provide an access token via the action's `repo-token` input to get a higher GitHub API request allocation to avoid rate limiting.

You will find the automatically generated `secrets.GITHUB_TOKEN` token to be convenient for this purpose. See the readme for an example of that:

https://github.com/arduino/setup-protoc#:~:text=to%20avoid%20rate%20limiting

**Comment by cnihelton** [comment]
What is the minimum set of permissions required for the token to still work?
