### ISSUE TITLE
Create release with Node 16.x support

### ISSUE THREAD

**Issue by elliotmakuh** [arduino/setup-protoc#68]
### Describe the request

Github is enforcing the use of Node 16 in Github Actions starting on May 18th at which point this action will fail to work.
(see post here: https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/)

It looks like this action has already been updated to support Node 16 as described in issue #59 .  A new release of the action needs to be published that includes the updated Node 16 support before May 18th.

I didn't want to open a duplicate issue but the issue #59 is locked and this is becoming an urgent issue.

### Describe the current behavior

`setup-protoc` runs on Node 12 and will fail to work starting on May 18th.

### 'arduino/setup-protoc' version

1.1.2

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/setup-protoc/issues?q=)
- [X] I verified the feature was still missing when using the latest version
- [X] My request contains all necessary details

**Comment by alessio-perugini** [comment]
@kim0 thx for the heads up we rushed the release. Any feedback if it's not breaking anything would be awesome. Sorry about that! :pray:

**Comment by alessio-perugini** [comment]
@zeisss thx for the test. You can now use the `v1` without being forced to ping the `@1.2.0` to pick up the latest version. Yesterday we forgot to update that branch. woopsi :sweat_smile:

**Comment by elliotmakuh** [comment]
Thanks for getting this taken care of!
