### ISSUE TITLE
Node.js 16 is being deprecated for actions

### ISSUE THREAD

**Issue by ctron** [arduino/setup-protoc#94]
### Describe the problem

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: arduino/setup-protoc@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

### To reproduce

Use `v2` in any github actions build

### Expected behavior

There should be an updated version

### 'arduino/setup-protoc' version

v2

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/setup-protoc/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

**Comment by alessio-perugini** [comment]
Published: https://github.com/arduino/setup-protoc/releases/tag/v3.0.0
Thank you for the heads up! :raised_hands:
